### ISSUE TITLE
"Can't fetch balance" when i go to send, though the wallet clearly knows my balance.

### ISSUE THREAD

**Issue by wheatshelf** [manuelsc/Lunary-Ethereum-Wallet#11]
Just as it says. When i open up Lunary, the wallet that was created when i initially ran the app shows my balance--it knows how much eth I've got and the corresponding USD continues to be accurate. So clearly the thing knows how much I've got. However, any attempt to send from that address gives me a notification along the bottom of the UI reading "can't fetch account balance." Suddenly I'm at zero eth the moment I try to move it to a more secure wallet where this nonsense doesn't happen. 
Why can't it "fetch" my balance when I hit SEND but seems to have fetched it just fine when I look at it?

**Comment by manuelsc** [comment]
I wasn't able to recreate this problem nor have I received a single similar report from another user. My best guess is you are just running an very outdated version of Lunary. Please update the app to the latest build (currently 1.29) and give it another try.

**Comment by wheatshelf** [comment]
Thought I was on the current version as the play store didn't show an update. Uninstalled 1.28 (play store),wiped caches, installed 1.29 from apk--same issue. Repeated
The uninstall and cache wipes, installed 1.29 again from F-droid.
Same results. Just did it again, have screenshots of the problem. Step by step. 

For reference, I'm using a Oneplus One, LineageOS 14.1. Rooted with Magisk. 

⁣Sent from TypeApp ​

**Comment by wheatshelf** [comment]
Anything? Any ideas? 

⁣Sent from TypeApp ​

**Comment by wheatshelf** [comment]
Here's an update: 
I gave Lunary my daily try, to see if anything had changed; it had. It permitted me to send to another wallet without "can't fetch balance"--i then input the wrong password for the wallet (confusing it with another wallet's password), and upon trying again I was re-met with the too-familiar "can't fetch balance" error. 

Progress? 

⁣Sent from TypeApp ​

**Comment by manuelsc** [comment]
I'm taking a closer look regarding your issue on Sunday, I'm currently on vacation until then. 
Sounds like you may experience some network problems, is the error displayed immediatly or after a few second delay? I'd suggest to try it on a different network connection or with/without wifi.
If you need to access your funds immediatly you can always export your wallet and import it in MEW or Mist, altough I'd like to fix this issue for you in Lunary. Please provide information on where this error is showing up, what kind of OS you are running and which device and your network connection type. Other apps or settings like VPN or proxies or custom dns settings would also be relevant. You can also email me if you don't want to disclose this information publically at contact@rehanced.com

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by manuelsc** [comment]
Fixed in Version 1.3
