### ISSUE TITLE
Add option to set pin code protecting only sending ETH

### ISSUE THREAD

**Issue by doronbehar** [manuelsc/Lunary-Ethereum-Wallet#14]
In the [FOSS bitcoin wallet](https://github.com/bitcoin-wallet/bitcoin-wallet) I use, there is a recommended option to set up a pin code that I'll have to enter before spending coins from my wallet. Will it be possible to see such an option in Lunry? I know I can set up a pattern password that will protect anyone from opening the app but sometimes I want to just view my balance or something a like and not nessecerally spend ETH.

**Comment by manuelsc** [comment]
Lunary already has this protection, in order to send funds you need to enter the password you set during the wallet creation process. As well as an additional feature that lets you lock the entire app with a pattern.
