### ISSUE TITLE
"Can't fetch account balances. Invalid response."

### ISSUE THREAD

**Issue by Rocaco** [manuelsc/Lunary-Ethereum-Wallet#15]
I'm getting this error when I'm trying to refresh my account balance. I see the wallet under the middle wallet tab, but I always get this error when trying to refresh my balance.

Also, I'm unable to export the wallet.  I get another error stating "No Full Wallet; Watch only wallets can not be exported." 

The wallet is my initial one I made during setup, so I know it's not a watch only wallet.

Using the latest version via F-Droid.

**Comment by manuelsc** [comment]
Fixed in Version 1.3
