### ISSUE TITLE
Setting gas price does not work

### ISSUE THREAD

**Issue by markasoftware** [manuelsc/Lunary-Ethereum-Wallet#27]
Whenever I set gas price to, for example, 2 Gwei, the actual transaction uses 11 Gwei. This seems pretty serious.

**Comment by manuelsc** [comment]
Please update to the latest version, this issue was fixed in 1.36

**Comment by markasoftware** [comment]
Ok, it's just not on F-Droid yet. Thanks!

**Comment by manuelsc** [comment]
There seems to be an extraordinary long delay between new builds on f-droid now. Lunarys metadata haven't been updated in over a month which worries me a bit. I'll look into that.
