### ISSUE TITLE
Request To Create a Privacy Policy and FAQs, 

### ISSUE THREAD

**Issue by Kelita** [manuelsc/Lunary-Ethereum-Wallet#35]
Hello, I'm Kelita. I would like to contribute to your project. I have been contributing to open source projects lately, and I wish to also add to yours. I noticed your project have no Privacy Policy and FAQs, which I will like to do that for you. 
A Privacy Policy lets users of the app know about the policies regarding end-users information collection and use. Also, FAQs will answer some question users might want to have and save both you and the users the stress of asking and you answering the same set of question over and over again. 

I would be waiting for your reply and will be glad if this is privileged is given to me.

**Comment by manuelsc** [comment]
Thank you for wanting to contribute. Just create a pull request and I'll gladly check and merge it

**Comment by Kelita** [comment]
Thanks so much. I have some few questions which I would like to ask, but
you already closed the issue.

I will want to know if you have anything in mind you will like to add to
the Privacy Policy and FAQs.
What I would also want to know is how you would want people to communicate
with you either via GitHub or email or any other means.

These are the few questions I have for now. I would also want you to
preview the files before I make a pull request.

**Comment by Kelita** [comment]
Hello, I have completed the work on the Privacy Policy. Please do well to
check if there is any need for correction.
https://docs.google.com/document/d/1k5vNWKWEBA9JD26rJPRqp4vpwTlzMV5pWhRepWOM3F8/edit#

**Comment by Kelita** [comment]
That first link won't open, use this one.
https://docs.google.com/document/d/1k5vNWKWEBA9JD26rJPRqp4vpwTlzMV5pWhRepWOM3F8/edit?usp=sharing
