### ISSUE TITLE
v1.38 won't open on Android 8.1.0

### ISSUE THREAD

**Issue by mikelsr** [manuelsc/Lunary-Ethereum-Wallet#37]
The app won't launch and Android will show the message: 

```
Lunary has stopped
(option) Open app again
```

- Lunary version: `1.38`
- OS: `LineageOS 15.1-20181016-NIGHTLY-oneplus3`
- Android version: `8.1.0`

**Comment by manuelsc** [comment]
Can you provide a crashlog and more details on the steps to reproduce?
I haven't been able to reproduce a crash on my devices

**Comment by mikelsr** [comment]
Here's the [log file](https://github.com/manuelsc/Lunary-Ethereum-Wallet/files/2500972/lunary.log), please tell me if you need anything else

**Comment by vandenbrande** [comment]
Hi, Thank you for contacting us.  This is a confirmation that your e-mail has been received. We will reply to your e-mail within 24-48 hours. Have a nice day!  Best regards,  ArduinoSensors.nl

**Comment by mikelsr** [comment]
Closed the issue because I don't think anyone else will have problems with this
