### ISSUE TITLE
Free license contradicted by additional conditions

### ISSUE THREAD

**Issue by bignose-debian** [manuelsc/Lunary-Ethereum-Wallet#4]
The declared license of Lunary is GNU GPL version 3. GPL v3 §2 says, in part:

> This License explicitly affirms your unlimited permission to run the unmodified Program.

That permission is affirmed whether or not the recipient agrees to any further conditions.

The Lunary program notifies the user that access to “the Service”, when run, refuses to continue until additional conditions are agreed:

>Your access to and use of the Service [Lunary Ether Wallet] is conditioned on your acceptance of and compliance with these Terms […] If you disagree with any part of the terms then you many not access the Service.

This restriction contradicts the unlimited permission already granted in use of the Lunary Ether Wallet, by granting the GPL v3 to the recipient.

Please remove the click-wrap that refuses access to the program without accepting additonal conditions.

**Comment by manuelsc** [comment]
Lunary currently relies on a bunch of third party apis such as etherscan.io, ethplorer.io and poloniex price api. Each and every one of those have their own terms of service and usage compliance given they are not run by us. Any restriction you find in our ToS are restrictions applying to those services, not Lunary itself. The other aspects as limitation of warranty and liability as well as clarifying the risks is already handled by the GPL itself, our ToS is just reaffirming those points.
It's not a contradiction with the GPL3 licence since we are not limiting or restricting the usage of this app itself. It's our legal defense in case a user abuses those third party apis and trys to blame it on Lunary.

**Comment by bignose-debian** [comment]
Thanks for the prompt response.

> Lunary currently relies on a bunch of third party apis such as etherscan.io, ethplorer.io and poloniex price api. Each and every one of those have their own terms of service and usage compliance given they are not run by us.

Okay. I understand now that the Lunary developers are acting to provide access to those services, via the Lunary program. It's right that the Lunary program should display those conditions of using those services.

But that's not how the conditions are presented; the program presents these as conditions of Lunary Ether Wallet.

Also, if a user rejects the conditions of those services, they should not be denied use of the Lunary Ether Wallet; the GNU GPL v3 has already granted unconditional permission to use the program.

Please alter the message so that it's clear these are conditions *only* of using the external services (not of using Lunary Ether Wallet).

**Comment by bignose-debian** [comment]
I can also raise a separate issue, requesting that the program can be used without one or all of those services if the user rejects the extra conditions. Should I do that now?

**Comment by manuelsc** [comment]
While I agree that it's not ideal I don't think that users should be able to opt in or opt out to those third parties. As mentioned above Lunary heavily relies on those APIs, if users revoke their permission the apps functionality is literally limited to wallet generation and exporting / importing. No balance fetches, no price data, no transaction history, no transaction sending, no address lookup, no tokens. That's not a good user experience if we split Lunary into "accepted third party" and "denied third party" as it eliminates the most important features of basic a wallet. 
That being said I acknowledge that Lunary is not doing a great job at expressing these conditions in a separate way. But the aspects of the ToS, even if applied to Lunary itself, are basically only conditions on liability, warranty and clarifications of risks. These points don't contradict with the GPL as these points are also covered under the licence.
Any restriction mentioned in the ToS is specifically directed to these third parties as covered in "SUSPENSION; TERMINATION" and "Links To Other Web Sites". Combine that with our privacy policy and a disclaimer and that's the whole text our users agree too. 
But just a quick heads up: We are working on a more abstract api integration which would allow other apis or web3 calls. This step gives users more choice, increase decentralization and is a reason to adapt our ToS anyway. So I'll keep this issue open until then.

**Comment by bignose-debian** [comment]
Thanks for explaining further.

> […] the aspects of the ToS, even if applied to Lunary itself, are basically only conditions on liability, warranty and clarifications of risks. These points don't contradict with the GPL as these points are also covered under the licence.

The problem currently is that the user is required to agree to additional conditions of use, and without that agreement the program refuses to operate. This effectively makes the work non-free, contradicting the GPL's unconditional grant of use.

The good news, I think, is that there is no need to make the program operation conditional on the user's agreement. Because these are, as you describe it, not conditions of use, but limits of your liability; that doesn't require the user to accept them, it's simply a declaration.

So, I think this can be resolved by:

* Change the message from describing conditions that must be agreed, to simply stating facts that must be acknowledged.
* Change the message from describing conditions on Lunary Ethereum Wallet, to instead state these are limits from the third-party services.
* Change the message from one which blocks access until “I agree”, to one which simply advises the reader to understand and then dismiss the message.

(I would attempt a merge request for these changes, but my quick search of the source code did not reveal where this message exists in the source. Can you help?)

Once those are done I think it will be much clearer that Lunary Ethereum Wallet has no extra conditions on use, and the liability limitations will still be notified to the user.

**Comment by manuelsc** [comment]
The message is located in the strings.xml for each language (even though the tos is only available in english, so it's currently redundant in every strings.xml). 
https://github.com/manuelsc/Lunary-Ethereum-Wallet/blob/master/app/src/main/res/values/strings.xml
https://github.com/manuelsc/Lunary-Ethereum-Wallet/blob/master/app/src/main/res/values-de/strings.xml
https://github.com/manuelsc/Lunary-Ethereum-Wallet/blob/master/app/src/main/res/values-es/strings.xml

I'm a developer and not a lawyer so I'd like to make sure that the most important points for limited liability, warranty and the mentioned risks are included in any form, meaning even applied to Lunary itself as defined and allowed by the GPL.

**Comment by n1trux** [comment]
Is there really no way to minimise the dependencies on third-party APIs?

This issue is the sole way I'm not installing/using Lunary.

**Comment by manuelsc** [comment]
ToS removed and replaced with GNU Licence in a8151e2fb5aa68c34810d21640c5780e3141fd27 (v1.33)
