### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [manuelsc/Lunary-Ethereum-Wallet#44]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 98 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on Lunary-Ethereum-Wallet (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve Lunary-Ethereum-Wallet's security, and the quality of the reports of static analysis tools.
(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by misterAnderson90** [comment]
Hello @manuelsc,

Are you interested in receiving this report or should I close this issue?

**Comment by manuelsc** [comment]
Hi,

thanks for letting me know and putting the effort in to make this project and it's users safe.

Lunary is discontinued for quite some while now and hasn't been actively developed in years. It might be the best way forward to simply pull the apk from github and fdroid and put an usage warning on the repo.

I do not encourage anyone to still use Lunary today and suggest to migrate to a more up to date wallet as soon as possible. Though I imagine most people probably already did a long time ago. If not, not is the time.

Thank you for reaching out to me though and sorry that I can't help you with your evaluations.

**Comment by misterAnderson90** [comment]
Thanks for your response, @manuelsc. 

Since this project is discontinued, I'm closing this issue.
