### ISSUE TITLE
Can't connect to the Network

### ISSUE THREAD

**Issue by flaggitoff** [manuelsc/Lunary-Ethereum-Wallet#6]
That's the error I'm getting.

Tried restarting the phone clearing the Lunary cache in System Prefs.

Bummer, because I am definitely connected to the network.

**Comment by flaggitoff** [comment]
Forgot to say , this is when I'm trying to send a transaction.

**Comment by manuelsc** [comment]
Is this problem persisting? This might have been only a temporary connection problem with etherscan.io's api or node. I'd suggest to give it another try, in case you still encounter this issue please write us an email with additional information about your transaction at contact@rehanced.com

**Comment by fazlerabbi37** [comment]
Hi there, I was playing around with app and imported an existing key but it keep showing this error. Would be kind of you if you can reopen it ans take a look at it.

**Comment by vandenbrande** [comment]
Hi, Thank you for contacting us.  This is a confirmation that your e-mail has been received. We will reply to your e-mail within 24-48 hours. Have a nice day!  Best regards,  ArduinoSensors.nl

**Comment by manuelsc** [comment]
@fazlerabbi37 Can you pull a log for me? Contact me at contact@rehanced.com

**Comment by fazlerabbi37** [comment]
@manuelsc do you mind if we keep the conversation here? 

---

Unfortunately, I can't pull the log using logcat :unamused:. Would it work if I give you ```adb shell logcat | grep com.rehanced.lunary``` dump???

**Comment by manuelsc** [comment]
@fazlerabbi37 Not at all, just an option to share your log in a less public way in case you want to.  

It shouldn't make any difference how you get it, package id is correct if that's your question.

**Comment by fazlerabbi37** [comment]
@manuelsc log sent over mail. :smile: 

 I thought you want to continue the conversation over mail on this issue when you said "Contact me at contact@rehanced.com". Really sorry for misunderstanding you and thank you for providing a safe way to sent log.

**Comment by manuelsc** [comment]
Fixed with latest build https://github.com/manuelsc/Lunary-Ethereum-Wallet/releases/tag/v1.39
