### ISSUE TITLE
Apparent issues with long passwords

### ISSUE THREAD

**Issue by gappleto97** [manuelsc/Lunary-Ethereum-Wallet#9]
Hi,

I made a wallet some time ago with a rather long password. It was autogenerated, and had special characters in it, if that makes a difference.

I made the keystore in geth. Geth and MyEtherWallet are able to unlock the wallet. Lunary is not.

**Comment by manuelsc** [comment]
Can you please provide a bit more information? The length of the password shouldn't matter as long as it consists of a minimum of 9 chars. 
For starters, what was the exact error Lunary showed you?
What did you use to generate the wallet and which version? Geth worked for me even with a long password and special characters.
Are we talking about a version 1 wallet? (version field inside the json file)?
